# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    #test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -AhlF'
alias la='ls -A'
alias l='ls -CF'
#alias rm='mv -f --target-directory=${HOME}/.recycle'
#eXchange Directory
alias xd='cd $OLDPWD'
alias ..='cd ..'
alias lsd='ls -d */ .*/'
alias minicom='minicom -l -L -w -c on -a on'
alias ec='emacsclient -t'
