#!/bin/sh
# tcs: tcs.py wrapper

tcs() {
    local f
    local PYTHON

    f=$(mktemp -q --suffix=.tcs)
    # /usr/bin/python or /usr/bin/python3
    PYTHON=`ls -1 /usr/bin/python* | head -1`

    $PYTHON ${HOME}/opt/lib/python/tcs.py $* $f

    if [ -e $f ]; then
	source $f
	rm -f $f
    fi
}

# init tcs
tcs init
